"""Slack notification script: formats anomaly summary as a Slack block message.

Called by session-complete-hook.sh when severity is Anomaly or Critical.
Reads the monitor output file, extracts anomaly data, and writes a Slack
message payload to notifications/slack-messages/.

If SLACK_WEBHOOK_URL is set in the environment, posts the message.
Otherwise, saves the payload as a JSON file for review.

Reference solution for Course 7, Lesson 4.
"""

import json
import os
import re
import sys
from datetime import datetime
from pathlib import Path


def extract_anomalies(content: str) -> list[dict]:
    """Pull anomaly rows from the monitor output."""
    anomalies = []
    # Match table rows: | Supplier | Transaction | Amount | Daily Avg | Multiple |
    pattern = r"\|\s*(.+?)\s*\|\s*(TXN\d+)\s*\|\s*\$([\d,]+\.\d+)\s*\|\s*\$([\d,]+\.\d+)\s*\|\s*([\d.]+)x\s*\|"
    for match in re.finditer(pattern, content):
        anomalies.append({
            "supplier": match.group(1).strip(),
            "transaction_id": match.group(2),
            "amount": match.group(3),
            "daily_avg": match.group(4),
            "multiple": match.group(5),
        })
    return anomalies


def build_slack_payload(monitor_file: str, content: str, anomalies: list) -> dict:
    """Build a Slack Block Kit message."""
    severity_match = re.search(r"\*\*Severity:\*\*\s*(\w+)", content)
    severity = severity_match.group(1) if severity_match else "Unknown"

    date_match = re.search(r"monitor-(\d{4}-\d{2}-\d{2})", monitor_file)
    monitor_date = date_match.group(1) if date_match else "unknown"

    emoji = ":rotating_light:" if severity == "Critical" else ":warning:"

    blocks = [
        {
            "type": "header",
            "text": {
                "type": "plain_text",
                "text": f"{emoji} Spend Monitor Alert: {severity}",
            },
        },
        {
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": f"*Date:* {monitor_date}\n*Anomalies detected:* {len(anomalies)}",
            },
        },
    ]

    # Add anomaly details
    for a in anomalies:
        blocks.append({
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": (
                    f"*{a['supplier']}*\n"
                    f"Transaction: {a['transaction_id']} | "
                    f"Amount: ${a['amount']} | "
                    f"Multiple: {a['multiple']}x daily avg"
                ),
            },
        })

    blocks.append({"type": "divider"})
    blocks.append({
        "type": "context",
        "elements": [
            {
                "type": "mrkdwn",
                "text": f"Source: {Path(monitor_file).name} | Generated by Claude Code",
            },
        ],
    })

    return {"blocks": blocks}


def main():
    if len(sys.argv) < 2:
        print("Usage: python slack-notify.py <monitor-file>")
        sys.exit(1)

    monitor_file = sys.argv[1]
    with open(monitor_file, "r", encoding="utf-8") as f:
        content = f.read()

    anomalies = extract_anomalies(content)
    payload = build_slack_payload(monitor_file, content, anomalies)

    # Save payload to file
    script_dir = Path(__file__).resolve().parent
    notifications_dir = script_dir.parent / "notifications" / "slack-messages"
    notifications_dir.mkdir(parents=True, exist_ok=True)

    date_match = re.search(r"monitor-(\d{4}-\d{2}-\d{2})", monitor_file)
    monitor_date = date_match.group(1) if date_match else datetime.now().strftime("%Y-%m-%d")
    output_path = notifications_dir / f"slack-{monitor_date}.json"

    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(payload, f, indent=2)
    print(f"Slack payload saved to {output_path}")

    # Post to Slack if webhook URL is configured
    webhook_url = os.environ.get("SLACK_WEBHOOK_URL")
    if webhook_url:
        import urllib.request
        req = urllib.request.Request(
            webhook_url,
            data=json.dumps(payload).encode("utf-8"),
            headers={"Content-Type": "application/json"},
        )
        try:
            urllib.request.urlopen(req)
            print("Posted to Slack successfully.")
        except Exception as e:
            print(f"Slack post failed: {e}")


if __name__ == "__main__":
    main()
